#!/bin/bash

# Watch the directory for new files
inotifywait -m /alx-system_engineering-devops/0x03-shell_variables_expansions -e create -e moved_to |
while read path action file; do
    # Check if the file is regular
    if [ -f "$path$file" ]; then
        chmod +x "$path$file"
        echo "Changed permissions for $file"
    fi
done

